### ISSUE TITLE
permission error on google cloud build

### ISSUE THREAD

**Issue by nicosandller** [movative/platformio-core-docker#2]
traceback:

```
starting build "cda01b41-8f5d-4ea7-9000-a0fc7eb18ab6"

FETCHSOURCE
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /workspace/.git/
From https://github.com/nicosandller/ac_control
 * branch            9f22271a4eac80f92e106273d36128a8b5de950a -> FETCH_HEAD
HEAD is now at 9f22271 updates docker image
BUILD
Pulling image: movative/platformio-core
Using default tag: latest
latest: Pulling from movative/platformio-core
d960726af2be: Pulling fs layer
e8d62473a22d: Pulling fs layer
8962bc0fad55: Pulling fs layer
65d943ee54c1: Pulling fs layer
532f6f723709: Pulling fs layer
1334e0fe2851: Pulling fs layer
062ada600c9e: Pulling fs layer
aec2e3a89371: Pulling fs layer
1ec7c3bcb4b2: Pulling fs layer
839e7acf0154: Pulling fs layer
c6850ac7282a: Pulling fs layer
aec2e3a89371: Waiting
1ec7c3bcb4b2: Waiting
839e7acf0154: Waiting
c6850ac7282a: Waiting
1334e0fe2851: Waiting
062ada600c9e: Waiting
e8d62473a22d: Verifying Checksum
e8d62473a22d: Download complete
8962bc0fad55: Verifying Checksum
8962bc0fad55: Download complete
d960726af2be: Verifying Checksum
d960726af2be: Download complete
1334e0fe2851: Verifying Checksum
1334e0fe2851: Download complete
65d943ee54c1: Verifying Checksum
65d943ee54c1: Download complete
062ada600c9e: Verifying Checksum
062ada600c9e: Download complete
aec2e3a89371: Verifying Checksum
aec2e3a89371: Download complete
1ec7c3bcb4b2: Verifying Checksum
1ec7c3bcb4b2: Download complete
c6850ac7282a: Verifying Checksum
c6850ac7282a: Download complete
839e7acf0154: Verifying Checksum
839e7acf0154: Download complete
532f6f723709: Verifying Checksum
532f6f723709: Download complete
d960726af2be: Pull complete
e8d62473a22d: Pull complete
8962bc0fad55: Pull complete
65d943ee54c1: Pull complete
532f6f723709: Pull complete
1334e0fe2851: Pull complete
062ada600c9e: Pull complete
aec2e3a89371: Pull complete
1ec7c3bcb4b2: Pull complete
839e7acf0154: Pull complete
c6850ac7282a: Pull complete
Digest: sha256:cfa96f32cfdec3d5fe70938393b555441cbfe6cb9429aaebe3de7fb7caedb58e
Status: Downloaded newer image for movative/platformio-core:latest
docker.io/movative/platformio-core:latest
Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/platformio/__main__.py", line 109, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/platformio/commands/__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/platformio/__main__.py", line 63, in cli
    maintenance.on_platformio_start(ctx, force, caller)
  File "/usr/local/lib/python3.9/site-packages/platformio/maintenance.py", line 48, in on_platformio_start
    telemetry.on_command()
  File "/usr/local/lib/python3.9/site-packages/platformio/telemetry.py", line 292, in on_command
    resend_backuped_reports()
  File "/usr/local/lib/python3.9/site-packages/platformio/telemetry.py", line 443, in resend_backuped_reports
    tm = app.get_state_item("telemetry", {})
  File "/usr/local/lib/python3.9/site-packages/platformio/app.py", line 191, in get_state_item
    with State() as state:
  File "/usr/local/lib/python3.9/site-packages/platformio/app.py", line 94, in __init__
    self.path = join(get_project_core_dir(), "appstate.json")
  File "/usr/local/lib/python3.9/site-packages/platformio/project/helpers.py", line 50, in get_project_core_dir
    return ProjectConfig.get_instance(
  File "/usr/local/lib/python3.9/site-packages/platformio/project/config.py", line 389, in get_optional_dir
    result = self._get_core_dir(exists)
  File "/usr/local/lib/python3.9/site-packages/platformio/project/config.py", line 380, in _get_core_dir
    raise e
  File "/usr/local/lib/python3.9/site-packages/platformio/project/config.py", line 374, in _get_core_dir
    os.makedirs(core_dir)
  File "/usr/local/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/builder/home/.platformio'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

ERROR
ERROR: build step 0 "movative/platformio-core" failed: step exited with non-zero status: 1
```

**Comment by movative** [comment]
Thanks for the request and sorry for the late response.
At the moment this project has two problems: the first is that docker.hub changed the autobuild feature and moved it behind the paywall, second is that I currently build only the latest and greatest from platformio package and the python image. 
I ll have to fix those two problems and then I can invest some time to investigate your problem.

**Comment by movative** [comment]
I altered the Dockerfile a bit and it should work now.
It would be nice when you write me some feedback.

**Comment by movative** [comment]
And you have to use the docker.io/movative/platformio-core-docker:latest or docker.io/movative/platformio-core-docker:5.2.3 images.
